new: grind-timer
tosuapp/counters pull request #16
Opened 2024-11-20 19:54 UTC by kiwec

livesplit-inspired timer for pp farmers (or content creators)

i'm too lazy to make a gif but it's exactly what you expect, it turns green and goes up

![grind-timer by kiwec](https://github.com/user-attachments/assets/9f40ff6c-4631-4fb1-ade7-1c6a9e059e9c)

2024-11-20 23:51 UTC, cyperdark requested changes

2024-11-20 23:51 UTC, cyperdark commented on counters/grind-timer by kiwec/index.html
> +        if(pause_time == 0) {
Feature request: add settings option to all count time outside play

https://github.com/tosuapp/tosu/wiki#settings-api

2024-11-20 23:51 UTC, cyperdark commented on counters/grind-timer by kiwec/index.html
> +      const socket = new WebSocket("ws://127.0.0.1:24050/websocket/v2");
preferable add reconnecting websocket, or socket.js:
https://github.com/tosuapp/tosu/wiki#socket-wrapper

2024-11-21 12:08 UTC, kiwec commented on counters/grind-timer by kiwec/index.html
> +        if(pause_time == 0) {
Can you clarify what this means? It already pauses the timer whenever you're not actively playing the map (except the pause screen, I didn't see any keys in the JSON for it).

2024-11-21 13:43 UTC, GabuTheDev commented on counters/grind-timer by kiwec/index.html
> +        if(pause_time == 0) {
> Can you clarify what this means? It already pauses the timer whenever you're not actively playing the map (except the pause screen, I didn't see any keys in the JSON for it).

Ck probably wants an option to make the timer always run, no matter the screen status. (Yours currently, as stated in the description the overlay, resets it's time when the user switches to another beatmap. Ck wants it to always count time)

2024-11-21 15:26 UTC, cyperdark commented on counters/grind-timer by kiwec/index.html
> +        if(pause_time == 0) {
^ yeah, and setting for it will be nice to have

2024-11-21 16:34 UTC, kiwec commented on counters/grind-timer by kiwec/index.html
> +        if(pause_time == 0) {
I added settings + a manual mode for the settings to be usable. You can only click the overlay from its dedicated page, but I don't think there's a better way to do it.

2024-12-05 16:21 UTC, cyperdark commented
oh shit i forgot, ping me tomorrow in discord

2024-12-08 12:34 UTC, cyperdark approved these changes

2024-12-08 12:34 UTC, merged