new: HitErrorMeter
tosuapp/counters pull request #17
Opened 2024-11-21 21:25 UTC by KapiWilq

## HitErrorMeter by KapiWilq

<a href="https://github.com/KapiWilq" target="_blank"><img height="35" src="https://img.shields.io/badge/github-000000?style=for-the-badge&logo=github&logoColor=white" /></a>  

|||
| ------------- | ------------- |
| For | ingame, obs-overlay |
| Compatible with | tosu |
| Size |  720x100 |

> Supports all rulesets! | Very customizable! | The overlay resolution/size is for the default settings (both the overlay and the in-game score meter) in the osu!mania ruleset with EZDT at OD0.

![mania_ruleset](https://github.com/user-attachments/assets/36737597-e39e-46f8-8381-7028f98ede1c) ![osu_ruleset](https://github.com/user-attachments/assets/d52e0e71-e765-482b-afdd-204f0c58247a)

2024-11-21 21:37 UTC, cyperdark requested changes

2024-11-21 21:37 UTC, cyperdark commented on counters/HitErrorMeter by KapiWilq/index.js
> +const socket = new WebSocketManager(`${location.host}`);
const socket = new WebSocketManager(location.host);

2024-11-21 21:37 UTC, cyperdark commented on counters/HitErrorMeter by KapiWilq/styles/main.css
> +@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap");
store font locally

2024-11-21 21:37 UTC, cyperdark commented on counters/HitErrorMeter by KapiWilq/js/hitErrorMeter.js
> +        const RGBA_REGEXP = /rgba?\((?<r>[.\d]+)[, ]+(?<g>[.\d]+)[, ]+(?<b>[.\d]+)(?:\s?[,\/]\s?(?<a>[.\d]+%?))?\)/;
you can avoid regex by using this:
```js
const [r, g, b, a] = text.replace('rgba(', '').replace('rgb(', '').replace('(', '').split(',').map(r => r.trim());
```


optional, need test

2024-11-21 21:37 UTC, cyperdark commented on counters/HitErrorMeter by KapiWilq/js/hitErrorMeter.js
> +            else if (this.client === 'mania' && this.isConvert)
client === mania?

2024-11-26 17:42 UTC, KapiWilq commented
drafting this until I get mania to be actually accurate ([see discussion](https://discord.com/channels/1056534107330445362/1284013170368843787/1311004610558955611))

2024-12-05 19:24 UTC, KapiWilq commented
should be ready to go now

2024-12-08 12:42 UTC, merged